dnl -*- autoconf -*-
# Macros needed to find dune-gfe and dependent libraries.  They are called by
# the macros in ${top_src_dir}/dependencies.m4, which is generated by
# "dunecontrol autogen"

# Additional checks needed to build dune-gfe
# This macro should be invoked by every module which depends on dune-gfe, as
# well as by dune-gfe itself
AC_DEFUN([DUNE_GFE_CHECKS],[])

# Additional checks needed to find dune-gfe
# This macro should be invoked by every module which depends on dune-gfe, but
# not by dune-gfe itself
AC_DEFUN([DUNE_GFE_CHECK_MODULE],
[
  DUNE_CHECK_MODULES([dune-gfe],[gfe/rotation.hh])
])
