---
image: duneci/dune:2.6

before_script:
  - duneci-install-module https://git.imp.fu-berlin.de/agnumpde/dune-solvers.git

dune-fufem--gcc:
  script:
  - dunecontrol --current all
  - dunecontrol --current make test

dune-fufem--clang:
  script:
  - CMAKE_FLAGS="-DCMAKE_CXX_COMPILER=/usr/bin/clang++" dunecontrol --current all
  - dunecontrol --current make test
