################################
# Dune module information file #
################################

#Name of the module
Module: dune-gfe
Version: svn
Maintainer: oliver.sander@tu-dresden.de
#depending on
Depends: dune-grid(>=2.9) dune-uggrid dune-istl dune-localfunctions dune-functions (>=2.9) dune-solvers dune-fufem dune-elasticity (>=2.9) dune-gmsh4
Suggests: dune-foamgrid dune-parmg dune-vtk dune-curvedgrid
