# $Id: $

SUBDIRS = coupling

AM_CPPFLAGS = @AM_CPPFLAGS@ -I$(top_srcdir)/..

srcincludedir = $(includedir)/dune/common
srcinclude_HEADERS = averagedistanceassembler.hh \
                     averageinterface.hh \
                     geodesicdifference.hh \
                     geodesicfeassembler.hh \
                     geodesicfefunctionadaptor.hh \
                     harmonicenergystiffness.hh \
                     localgeodesicfefunction.hh \
                     localgeodesicfestiffness.hh \
                     maxnormtrustregion.hh \
                     quaternion.hh \
                     realtuple.hh \
                     riemanniantrsolver.hh \
                     rigidbodymotion.hh \
                     rodassembler.hh \
                     rodfactory.hh \
                     rodlocalstiffness.hh \
                     rodwriter.hh \
                     rotation.hh \
                     svd.hh \
                     targetspacertrsolver.hh \
                     tensor3.hh \
                     unitvector.hh

include $(top_srcdir)/am/global-rules
