# $Id: $

SUBDIRS = coupling

AM_CPPFLAGS = @AM_CPPFLAGS@ -I$(top_srcdir)/..

srcincludedir = $(includedir)/dune/common
srcinclude_HEADERS = adolcnamespaceinjections.hh \
                     averagedistanceassembler.hh \
                     averageinterface.hh \
                     cosseratvtkwriter.hh \
                     cosseratvtkreader.hh \
                     geodesicdifference.hh \
                     geodesicfeassembler.hh \
                     geodesicfefunctionadaptor.hh \
                     globalgeodesicfefunction.hh \
                     globalgfetestfunctionbasis.hh \
                     globalgfetestfunction.hh \
                     harmonicenergystiffness.hh \
                     hyperbolichalfspacepoint.hh \
                     linearalgebra.hh \
                     localgeodesicfefunction.hh \
                     localgeodesicfestiffness.hh \
                     localgeodesicfefdstiffness.hh \
                     localgfetestfunctionbasis.hh \
                     localprojectedfefunction.hh \
                     maxnormtrustregion.hh \
                     orthogonalmatrix.hh \
                     quaternion.hh \
                     realtuple.hh \
                     riemanniantrsolver.hh \
                     rigidbodymotion.hh \
                     rodassembler.hh \
                     rodfactory.hh \
                     rodlocalstiffness.hh \
                     rodwriter.hh \
                     rotation.hh \
                     skewmatrix.hh \
                     svd.hh \
                     targetspacertrsolver.hh \
                     tensorssd.hh \
                     tensor3.hh \
                     trustregionmmgbasesolver.hh \
                     trustregionsolver.hh \
                     trustregionsolver.cc \
                     unitvector.hh \
                     vtkfile.hh

include $(top_srcdir)/am/global-rules
