# $Id: Makefile.am 5716 2009-11-20 12:23:19Z dedner $

SUBDIRS =

AM_CPPFLAGS = @AM_CPPFLAGS@ -I$(top_srcdir)/..

srcincludedir = $(includedir)/dune/common
srcinclude_HEADERS = averagedistanceassembler.hh localgeodesicfefunction.hh \
                     quaternion.hh rodrefine.hh averageinterface.hh \
                     localgeodesicfestiffness.hh riemanniantrsolver.hh rodwriter.hh \
                     geodesicdifference.hh makestraightrod.hh rigidbodymotion.hh \
                     rotation.hh geodesicfeassembler.hh maxnormtrustregion.hh \
                     rodassembler.hh svd.hh harmonicenergystiffness.hh \
                     planarrodassembler.hh  rodlocalstiffness.hh  targetspacertrsolver.hh

include $(top_srcdir)/am/global-rules
